-- Run as S_IANLEONG. Application runtime continues to use DS_MASK.
CREATE TABLE MLOPS_POPULATION_SAMPLING_TEST (
    CUSTOMER_ID VARCHAR2(32) NOT NULL,
    YYYYMM VARCHAR2(6) NOT NULL,
    PRODUCT VARCHAR2(128) NOT NULL,
    SOURCE_SEGMENT VARCHAR2(32) NOT NULL,
    Y NUMBER(1) NOT NULL,
    ELIGIBILITY_TAG NUMBER(1) NOT NULL,
    CONSTRAINT CK_MLOPS_SAMP_TEST_SEGMENT_V2
        CHECK (SOURCE_SEGMENT IN ('潛客', '非潛客', '不分潛客')),
    CONSTRAINT UQ_MLOPS_POP_SAMPLING_TEST
        UNIQUE (YYYYMM, PRODUCT, SOURCE_SEGMENT, CUSTOMER_ID)
        USING INDEX COMPRESS 3
);

GRANT SELECT, INSERT, DELETE
ON MLOPS_POPULATION_SAMPLING_TEST TO DS_MASK;
