
DELETE FROM DS_SEC.CF_DGT1 WHERE YYYYMM = :ym;
DELETE FROM DS_SEC.CF_DGT2 WHERE YYYYMM = :ym;

--------------------------------------------------- 數位軌跡特徵 --------------------------------------------
CREATE TABLE PHW_CI_NEW AS
SELECT SNAP_YYYYMM
    ,PARTY_ID_MASK AS PARTY_ID
    ,A.LANDING_PAGE_ID
    ,B.LANDING_PAGE_DESC
    ,CEIL(AVG_L7D_CLICK_CNT * TO_NUMBER(TO_CHAR(LAST_CLICK_DATE,'dd'))) MONTH_ALL_CLICK
    ,CEIL(L1M_MED_CLICK_CNT * TO_NUMBER(TO_CHAR(LAST_CLICK_DATE,'dd'))/ TO_NUMBER(TO_CHAR(LAST_DAY( LAST_CLICK_DATE ),'dd'))) MONTH_MID_CLICK
FROM DM_S_VIEW.M_CI_CUST_LPAGE_HIT A
LEFT JOIN (
SELECT DISTINCT LANDING_PAGE_ID,LANDING_PAGE_DESC FROM DM_S_VIEW.M_CI_LPAGE
WHERE E_CHANNEL_CODE = '001' )B
ON A.LANDING_PAGE_ID = B.LANDING_PAGE_ID
INNER JOIN (SELECT DISTINCT PARTY_ID,PARTY_ID_MASK FROM DM_S_VIEW.M_AC_ACCOUNT) C
ON A.PARTY_ID = C.PARTY_ID
WHERE SNAP_YYYYMM BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND :ym AND TO_CHAR(LAST_CLICK_DATE,'yyyymm') = SNAP_YYYYMM AND E_CHANNEL_CODE = '001';


INSERT INTO DS_SEC.CF_DGT1
WITH 
--------------------------------帳務
DGT_T1 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_ACCT_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_ACCT_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_MID_CLICK ELSE 0 END) DGT_ACCT_MID_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_MID_CLICK ELSE 0 END) DGT_ACCT_MID_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T2 ELSE NULL END) DGT_ACCT_FCT_CNT_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T2 ELSE NULL END) DGT_ACCT_FCT_CNT_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_ACCT_FREQTFCT_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T2 ELSE NULL END) DGT_ACCT_FREQTFCT
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND (T2 LIKE '證券-%' OR T2 IN ('訂閱中心','線上變更基本資料','線上簽署','聯絡營業員')) THEN MONTH_ALL_CLICK ELSE NULL END)DGT_ACCT_ST_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND (T2 LIKE '期權-%' OR T2 IN ('權益數查詢','出入金及查詢','線上變更基本資料(期貨)','線上簽署(期貨)','國內外交易額度調整申請')) THEN MONTH_ALL_CLICK ELSE NULL END)DGT_ACCT_FO_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T2 LIKE '外期-%' THEN MONTH_ALL_CLICK ELSE NULL END)DGT_ACCT_GF_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND (T2 LIKE '海外%-%' OR T2 IN ('線上簽署(複委託)')) THEN MONTH_ALL_CLICK ELSE NULL END)DGT_ACCT_FS_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND (T2 LIKE '證券-%' OR T2 IN ('訂閱中心','線上變更基本資料','線上簽署','聯絡營業員')) THEN MONTH_ALL_CLICK ELSE NULL END)DGT_ACCT_ST_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND (T2 LIKE '期權-%' OR T2 IN ('權益數查詢','出入金及查詢','線上變更基本資料(期貨)','線上簽署(期貨)','國內外交易額度調整申請')) THEN MONTH_ALL_CLICK ELSE NULL END)DGT_ACCT_FO_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T2 LIKE '外期-%' THEN MONTH_ALL_CLICK ELSE NULL END)DGT_ACCT_GF_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND (T2 LIKE '海外%-%' OR T2 IN ('線上簽署(複委託)')) THEN MONTH_ALL_CLICK ELSE NULL END)DGT_ACCT_FS_PROD_L
    FROM(
    SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T2)SORTED FROM(
        SELECT A.*
              ,SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) L1
              ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,1)+1, INSTR(LANDING_PAGE_ID, '|',1,2)-INSTR(LANDING_PAGE_ID, '|',1,1)-1) )L2
              ,SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1)  T1
              ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,1)+1, INSTR(LANDING_PAGE_DESC, '|',1,2)-INSTR(LANDING_PAGE_DESC, '|',1,1)-1) )T2
        FROM  PHW_CI_NEW A
        WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) IN('v54','v55')
    )A   
    WHERE T2 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)
--------------------------------個股盤後
, DGT_T2 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STAFTH_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STAFTH_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_MID_CLICK ELSE 0 END) DGT_STAFTH_MID_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_MID_CLICK ELSE 0 END) DGT_STAFTH_MID_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T2 ELSE NULL END) DGT_STAFTH_FCT_CNT_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T2 ELSE NULL END) DGT_STAFTH_FCT_CNT_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_STAFTH_FREQTFCT_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T2 ELSE NULL END) DGT_STAFTH_FREQTFCT
    FROM(
    SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T2)SORTED FROM(
        SELECT A.*
              ,SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) L1
              ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,1)+1, INSTR(LANDING_PAGE_ID, '|',1,2)-INSTR(LANDING_PAGE_ID, '|',1,1)-1) )L2
              ,SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1)  T1
              ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,1)+1, INSTR(LANDING_PAGE_DESC, '|',1,2)-INSTR(LANDING_PAGE_DESC, '|',1,1)-1) )T2
        FROM  PHW_CI_NEW A
        WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) IN('v64')
    )A   
    WHERE T2 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)
--------------------------------智慧選股
, DGT_T3 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_SMTSTP_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_SMTSTP_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_MID_CLICK ELSE 0 END) DGT_SMTSTP_MID_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_MID_CLICK ELSE 0 END) DGT_SMTSTP_MID_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T2 ELSE NULL END) DGT_SMTSTP_FCT_CNT_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T2 ELSE NULL END) DGT_SMTSTP_FCT_CNT_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_SMTSTP_FREQTFCT_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T2 ELSE NULL END) DGT_SMTSTP_FREQTFCT
    FROM(
    SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T2)SORTED FROM(
        SELECT A.*
              ,SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) L1
              ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,1)+1, INSTR(LANDING_PAGE_ID, '|',1,2)-INSTR(LANDING_PAGE_ID, '|',1,1)-1) )L2
              ,SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1)  T1
              ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,1)+1, INSTR(LANDING_PAGE_DESC, '|',1,2)-INSTR(LANDING_PAGE_DESC, '|',1,1)-1) )T2
        FROM  PHW_CI_NEW A
        WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) IN('v43')
    )A   
    WHERE T2 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)

--------------------------------盤後資料_內容頁
, DGT_T4 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_AFTHIF_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_AFTHIF_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_MID_CLICK ELSE 0 END) DGT_AFTHIF_MID_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_MID_CLICK ELSE 0 END) DGT_AFTHIF_MID_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T2 ELSE NULL END) DGT_AFTHIF_FCT_CNT_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T2 ELSE NULL END) DGT_AFTHIF_FCT_CNT_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_AFTHIF_FREQTFCT_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T2 ELSE NULL END) DGT_AFTHIF_FREQTFCT
    FROM(
    SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T2)SORTED FROM(
        SELECT A.*
              ,SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) L1
              ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,1)+1, INSTR(LANDING_PAGE_ID, '|',1,2)-INSTR(LANDING_PAGE_ID, '|',1,1)-1) )L2
              ,SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1)  T1
              ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,1)+1, INSTR(LANDING_PAGE_DESC, '|',1,2)-INSTR(LANDING_PAGE_DESC, '|',1,1)-1) )T2
        FROM  PHW_CI_NEW A
        WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) IN('v31')
    )A   
    WHERE T2 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)

--------------------------------其他大項
, DGT_T5 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END)DGT_ALL_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END)DGT_ALL_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND LANDING_PAGE_DESC LIKE '市場行情_零股專區%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_ODDLOT_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND LANDING_PAGE_DESC LIKE '市場行情_零股專區%' THEN MONTH_ALL_CLICK ELSE 0 END) DGT_ODDLOT_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND LANDING_PAGE_DESC LIKE '市場行情_零股專區%' THEN MONTH_MID_CLICK ELSE 0 END) DGT_ODDLOT_MID_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND LANDING_PAGE_DESC LIKE '市場行情_零股專區%' THEN MONTH_MID_CLICK ELSE 0 END) DGT_ODDLOT_MID_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND LANDING_PAGE_DESC LIKE '新聞%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_NEWS_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND LANDING_PAGE_DESC LIKE '新聞%' THEN MONTH_ALL_CLICK ELSE 0 END) DGT_NEWS_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND LANDING_PAGE_DESC LIKE '新聞%' THEN MONTH_MID_CLICK ELSE 0 END) DGT_NEWS_MID_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND LANDING_PAGE_DESC LIKE '新聞%' THEN MONTH_MID_CLICK ELSE 0 END) DGT_NEWS_MID_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND LANDING_PAGE_DESC LIKE '%自選%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_OPTNL_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND LANDING_PAGE_DESC LIKE '%自選%' THEN MONTH_ALL_CLICK ELSE 0 END) DGT_OPTNL_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND LANDING_PAGE_DESC LIKE '%自選%' THEN MONTH_MID_CLICK ELSE 0 END) DGT_OPTNL_MID_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND LANDING_PAGE_DESC LIKE '%自選%' THEN MONTH_MID_CLICK ELSE 0 END) DGT_OPTNL_MID_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND LANDING_PAGE_DESC LIKE '權證資訊_%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_WAIF_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND LANDING_PAGE_DESC LIKE '權證資訊_%' THEN MONTH_ALL_CLICK ELSE 0 END) DGT_WAIF_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND LANDING_PAGE_DESC LIKE '權證資訊_%' THEN MONTH_MID_CLICK ELSE 0 END) DGT_WAIF_MID_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND LANDING_PAGE_DESC LIKE '權證資訊_%' THEN MONTH_MID_CLICK ELSE 0 END) DGT_WAIF_MID_PROD_L
    FROM(
    SELECT A.*
          ,SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) L1
          ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,1)+1, INSTR(LANDING_PAGE_ID, '|',1,2)-INSTR(LANDING_PAGE_ID, '|',1,1)-1) )L2
          ,SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1)  T1
          ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,1)+1, INSTR(LANDING_PAGE_DESC, '|',1,2)-INSTR(LANDING_PAGE_DESC, '|',1,1)-1) )T2
    FROM  PHW_CI_NEW A
    WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) != 'v00'
    )A
    GROUP BY PARTY_ID
)
--------------------------------個股報價
, DGT_T6 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T3 ELSE NULL END) DGT_STQT_TPS_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T3 ELSE NULL END) DGT_STQT_TPS_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_STQT_FQTPS_M_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T3 ELSE NULL END) DGT_STQT_FQTPS_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('ETF') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP1_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('半導體業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP2_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('電腦週邊','電腦及週邊設備業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP3_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('電子組件','電子零組件業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP4_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('光電業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP5_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('航運業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP6_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('金融保險','金融業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP7_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('指數類') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP8_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('通信網路','通信網路業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP9_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('其他電子','其他電子業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP10_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('生技醫療') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP11_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('鋼鐵工業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP12_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('電機機械') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP13_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('其它','其他') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP14_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('電子通路','電子通路業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP15_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('汽車工業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP16_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('建材營造') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP17_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('塑膠工業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP18_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('化學工業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP19_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('資訊服務','資訊服務業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP20_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('觀光事業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP21_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('電器電纜') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP22_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('食品工業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP23_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('水泥工業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP24_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('文化創意業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP25_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('紡織纖維') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP26_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('貿易百貨') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP27_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('造紙工業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP28_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('橡膠工業') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP29_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('油電燃氣') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP30_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('存託憑證') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP31_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('創新板') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP32_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('玻璃陶瓷') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP33_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('ETN') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STQT_TP34_PROD_M
    FROM(
        SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T3)SORTED FROM(
            SELECT SNAP_YYYYMM
                  ,PARTY_ID
                  ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,2)+1, INSTR(LANDING_PAGE_ID, '|',1,3)-INSTR(LANDING_PAGE_ID, '|',1,2)-1) )L3
                  ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,2)+1, INSTR(LANDING_PAGE_DESC, '|',1,3)-INSTR(LANDING_PAGE_DESC, '|',1,2)-1) )T3
                  ,SUM(MONTH_ALL_CLICK)MONTH_ALL_CLICK
                  ,SUM(MONTH_MID_CLICK)MONTH_MID_CLICK
            FROM  PHW_CI_NEW A
            WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) IN ('v06','v07','v08')
            GROUP BY SNAP_YYYYMM,PARTY_ID,SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,2)+1, INSTR(LANDING_PAGE_ID, '|',1,3)-INSTR(LANDING_PAGE_ID, '|',1,2)-1),SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,2)+1, INSTR(LANDING_PAGE_DESC, '|',1,3)-INSTR(LANDING_PAGE_DESC, '|',1,2)-1)
            )A
        WHERE T3 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)
SELECT A.CUSTOMER_ID
      ,A.YYYYMM
      ----------------------------全軌跡
      ,NVL(DGT_ALL_PROD_M,0) DGT_ALL_PROD_M
      ,CASE WHEN NVL(DGT_ALL_PROD_M,0)=0 AND NVL(DGT_ALL_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_ALL_PROD_M,0) - NVL(DGT_ALL_PROD_L,0) END DGT_ALL_PROD_M_MDIFF
      
      ----------------------------帳務
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_ACCT_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_ACCT_PROD_M_RATIO
      ,NVL(DGT_ACCT_PROD_M,0) DGT_ACCT_PROD_M
      ,CASE WHEN NVL(DGT_ACCT_PROD_M,0)=0 AND NVL(DGT_ACCT_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_ACCT_PROD_M,0) - NVL(DGT_ACCT_PROD_L,0) END DGT_ACCT_PROD_M_MDIFF
      ,NVL(DGT_ACCT_MID_PROD_M,0) DGT_ACCT_MID_PROD_M
      ,NVL(DGT_ACCT_FCT_CNT_M,0) DGT_ACCT_FCT_CNT_M
      ,CASE WHEN NVL(DGT_ACCT_FCT_CNT_M,0)=0 AND NVL(DGT_ACCT_FCT_CNT_L,0)=0 THEN NULL ELSE NVL(DGT_ACCT_FCT_CNT_M,0) - NVL(DGT_ACCT_FCT_CNT_L,0) END DGT_ACCT_FCT_CNT_M_MDIFF
      ,DGT_ACCT_FREQTFCT_RATIO
      ,DGT_ACCT_FREQTFCT
      ,NVL(DGT_ACCT_ST_PROD_M,0)DGT_ACCT_ST_PROD_M
      ,CASE WHEN NVL(DGT_ACCT_ST_PROD_M,0)=0 AND NVL(DGT_ACCT_ST_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_ACCT_ST_PROD_M,0) - NVL(DGT_ACCT_ST_PROD_L,0) END DGT_ACCT_ST_PROD_M_MDIFF
      ,NVL(DGT_ACCT_FO_PROD_M,0)DGT_ACCT_FO_PROD_M
      ,CASE WHEN NVL(DGT_ACCT_FO_PROD_M,0)=0 AND NVL(DGT_ACCT_FO_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_ACCT_FO_PROD_M,0) - NVL(DGT_ACCT_FO_PROD_L,0) END DGT_ACCT_FO_PROD_M_MDIFF
      ,NVL(DGT_ACCT_GF_PROD_M,0)DGT_ACCT_GF_PROD_M
      ,CASE WHEN NVL(DGT_ACCT_GF_PROD_M,0)=0 AND NVL(DGT_ACCT_GF_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_ACCT_GF_PROD_M,0) - NVL(DGT_ACCT_GF_PROD_L,0) END DGT_ACCT_GF_PROD_M_MDIFF
      ,NVL(DGT_ACCT_FS_PROD_M,0)DGT_ACCT_FS_PROD_M
      ,CASE WHEN NVL(DGT_ACCT_FS_PROD_M,0)=0 AND NVL(DGT_ACCT_FS_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_ACCT_FS_PROD_M,0) - NVL(DGT_ACCT_FS_PROD_L,0) END DGT_ACCT_FS_PROD_M_MDIFF
      
      ----------------------------個股盤後
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_STAFTH_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_STAFTH_PROD_M_RATIO
      ,NVL(DGT_STAFTH_PROD_M,0)DGT_STAFTH_PROD_M
      ,CASE WHEN NVL(DGT_STAFTH_PROD_M,0)=0 AND NVL(DGT_STAFTH_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STAFTH_PROD_M,0) - NVL(DGT_STAFTH_PROD_L,0) END DGT_STAFTH_PROD_M_MDIFF
      ,NVL(DGT_STAFTH_MID_PROD_M,0) DGT_STAFTH_MID_PROD_M
      ,NVL(DGT_STAFTH_FCT_CNT_M,0) DGT_STAFTH_FCT_CNT_M
      ,CASE WHEN NVL(DGT_STAFTH_FCT_CNT_M,0)=0 AND NVL(DGT_STAFTH_FCT_CNT_L,0)=0 THEN NULL ELSE NVL(DGT_STAFTH_FCT_CNT_M,0) - NVL(DGT_STAFTH_FCT_CNT_L,0) END DGT_STAFTH_FCT_CNT_M_MDIFF
      ,DGT_STAFTH_FREQTFCT_RATIO
      ,DGT_STAFTH_FREQTFCT
      
      ----------------------------智慧選股
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_SMTSTP_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_SMTSTP_PROD_M_RATIO
      ,NVL(DGT_SMTSTP_PROD_M,0)DGT_SMTSTP_PROD_M
      ,CASE WHEN NVL(DGT_SMTSTP_PROD_M,0)=0 AND NVL(DGT_SMTSTP_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_SMTSTP_PROD_M,0) - NVL(DGT_SMTSTP_PROD_L,0) END DGT_SMTSTP_PROD_M_MDIFF
      ,NVL(DGT_SMTSTP_MID_PROD_M,0) DGT_SMTSTP_MID_PROD_M
      ,NVL(DGT_SMTSTP_FCT_CNT_M,0) DGT_SMTSTP_FCT_CNT_M
      ,CASE WHEN NVL(DGT_SMTSTP_FCT_CNT_M,0)=0 AND NVL(DGT_SMTSTP_FCT_CNT_L,0)=0 THEN NULL ELSE NVL(DGT_SMTSTP_FCT_CNT_M,0) - NVL(DGT_SMTSTP_FCT_CNT_L,0) END DGT_SMTSTP_FCT_CNT_M_MDIFF
      ,DGT_SMTSTP_FREQTFCT_RATIO
      ,DGT_SMTSTP_FREQTFCT
      
      ----------------------------盤後資料_內容頁
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_AFTHIF_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_AFTHIF_PROD_M_RATIO
      ,NVL(DGT_AFTHIF_PROD_M,0)DGT_AFTHIF_PROD_M
      ,CASE WHEN NVL(DGT_AFTHIF_PROD_M,0)=0 AND NVL(DGT_AFTHIF_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_AFTHIF_PROD_M,0) - NVL(DGT_AFTHIF_PROD_L,0) END DGT_AFTHIF_PROD_M_MDIFF
      ,NVL(DGT_AFTHIF_MID_PROD_M,0) DGT_AFTHIF_MID_PROD_M
      ,NVL(DGT_AFTHIF_FCT_CNT_M,0) DGT_AFTHIF_FCT_CNT_M
      ,CASE WHEN NVL(DGT_AFTHIF_FCT_CNT_M,0)=0 AND NVL(DGT_AFTHIF_FCT_CNT_L,0)=0 THEN NULL ELSE NVL(DGT_AFTHIF_FCT_CNT_M,0) - NVL(DGT_AFTHIF_FCT_CNT_L,0) END DGT_AFTHIF_FCT_CNT_M_MDIFF
      ,DGT_AFTHIF_FREQTFCT_RATIO
      ,DGT_AFTHIF_FREQTFCT
      
      ----------------------------其他大項
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_ODDLOT_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_ODDLOT_PROD_M_RATIO
      ,NVL(DGT_ODDLOT_PROD_M,0)DGT_ODDLOT_PROD_M
      ,CASE WHEN NVL(DGT_ODDLOT_PROD_M,0)=0 AND NVL(DGT_ODDLOT_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_ODDLOT_PROD_M,0) - NVL(DGT_ODDLOT_PROD_L,0) END DGT_ODDLOT_PROD_M_MDIFF
      ,NVL(DGT_ODDLOT_MID_PROD_M,0)DGT_ODDLOT_MID_PROD_M
      
      
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_NEWS_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_NEWS_PROD_M_RATIO
      ,NVL(DGT_NEWS_PROD_M,0)DGT_NEWS_PROD_M
      ,CASE WHEN NVL(DGT_NEWS_PROD_M,0)=0 AND NVL(DGT_NEWS_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_NEWS_PROD_M,0) - NVL(DGT_NEWS_PROD_L,0) END DGT_NEWS_PROD_M_MDIFF
      ,NVL(DGT_NEWS_MID_PROD_M,0)DGT_NEWS_MID_PROD_M
      
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_OPTNL_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_OPTNL_PROD_M_RATIO
      ,NVL(DGT_OPTNL_PROD_M,0)DGT_OPTNL_PROD_M
      ,CASE WHEN NVL(DGT_OPTNL_PROD_M,0)=0 AND NVL(DGT_OPTNL_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_OPTNL_PROD_M,0) - NVL(DGT_OPTNL_PROD_L,0) END DGT_OPTNL_PROD_M_MDIFF
      ,NVL(DGT_OPTNL_MID_PROD_M,0)DGT_OPTNL_MID_PROD_M
      
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_WAIF_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_WAIF_PROD_M_RATIO
      ,NVL(DGT_WAIF_PROD_M,0)DGT_WAIF_PROD_M
      ,CASE WHEN NVL(DGT_WAIF_PROD_M,0)=0 AND NVL(DGT_WAIF_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_WAIF_PROD_M,0) - NVL(DGT_WAIF_PROD_L,0) END DGT_WAIF_PROD_M_MDIFF
      ,NVL(DGT_WAIF_MID_PROD_M,0)DGT_WAIF_MID_PROD_M
      
      ----------------------------個股報價
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_STQT_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_STQT_PROD_M_RATIO
      ,NVL(DGT_STQT_PROD_M,0)DGT_STQT_PROD_M
      ,CASE WHEN NVL(DGT_STQT_PROD_M,0)=0 AND NVL(DGT_STQT_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STQT_PROD_M,0) - NVL(DGT_STQT_PROD_L,0) END DGT_STQT_PROD_M_MDIFF
      ,NVL(DGT_STQT_TPS_M,0) DGT_STQT_TPS_M
      ,CASE WHEN NVL(DGT_STQT_TPS_M,0)=0 AND NVL(DGT_STQT_TPS_L,0)=0 THEN NULL ELSE NVL(DGT_STQT_TPS_M,0) - NVL(DGT_STQT_TPS_L,0) END DGT_STQT_TPS_M_MDIFF
      ,DGT_STQT_FQTPS_M_RATIO
      ,DGT_STQT_FQTPS_M
      ,NVL(DGT_STQT_TP1_PROD_M,0) DGT_STQT_TP1_PROD_M
      ,NVL(DGT_STQT_TP2_PROD_M,0) DGT_STQT_TP2_PROD_M
      ,NVL(DGT_STQT_TP3_PROD_M,0) DGT_STQT_TP3_PROD_M
      ,NVL(DGT_STQT_TP4_PROD_M,0) DGT_STQT_TP4_PROD_M
      ,NVL(DGT_STQT_TP5_PROD_M,0) DGT_STQT_TP5_PROD_M
      ,NVL(DGT_STQT_TP6_PROD_M,0) DGT_STQT_TP6_PROD_M
      ,NVL(DGT_STQT_TP7_PROD_M,0) DGT_STQT_TP7_PROD_M
      ,NVL(DGT_STQT_TP8_PROD_M,0) DGT_STQT_TP8_PROD_M
      ,NVL(DGT_STQT_TP9_PROD_M,0) DGT_STQT_TP9_PROD_M
      ,NVL(DGT_STQT_TP10_PROD_M,0) DGT_STQT_TP10_PROD_M
      ,NVL(DGT_STQT_TP11_PROD_M,0) DGT_STQT_TP11_PROD_M
      ,NVL(DGT_STQT_TP12_PROD_M,0) DGT_STQT_TP12_PROD_M
      ,NVL(DGT_STQT_TP13_PROD_M,0) DGT_STQT_TP13_PROD_M
      ,NVL(DGT_STQT_TP14_PROD_M,0) DGT_STQT_TP14_PROD_M
      ,NVL(DGT_STQT_TP15_PROD_M,0) DGT_STQT_TP15_PROD_M
      ,NVL(DGT_STQT_TP16_PROD_M,0) DGT_STQT_TP16_PROD_M
      ,NVL(DGT_STQT_TP17_PROD_M,0) DGT_STQT_TP17_PROD_M
      ,NVL(DGT_STQT_TP18_PROD_M,0) DGT_STQT_TP18_PROD_M
      ,NVL(DGT_STQT_TP19_PROD_M,0) DGT_STQT_TP19_PROD_M
      ,NVL(DGT_STQT_TP20_PROD_M,0) DGT_STQT_TP20_PROD_M
      ,NVL(DGT_STQT_TP21_PROD_M,0) DGT_STQT_TP21_PROD_M
      ,NVL(DGT_STQT_TP22_PROD_M,0) DGT_STQT_TP22_PROD_M
      ,NVL(DGT_STQT_TP23_PROD_M,0) DGT_STQT_TP23_PROD_M
      ,NVL(DGT_STQT_TP24_PROD_M,0) DGT_STQT_TP24_PROD_M
      ,NVL(DGT_STQT_TP25_PROD_M,0) DGT_STQT_TP25_PROD_M
      ,NVL(DGT_STQT_TP26_PROD_M,0) DGT_STQT_TP26_PROD_M
      ,NVL(DGT_STQT_TP27_PROD_M,0) DGT_STQT_TP27_PROD_M
      ,NVL(DGT_STQT_TP28_PROD_M,0) DGT_STQT_TP28_PROD_M
      ,NVL(DGT_STQT_TP29_PROD_M,0) DGT_STQT_TP29_PROD_M
      ,NVL(DGT_STQT_TP30_PROD_M,0) DGT_STQT_TP30_PROD_M
      ,NVL(DGT_STQT_TP31_PROD_M,0) DGT_STQT_TP31_PROD_M
      ,NVL(DGT_STQT_TP32_PROD_M,0) DGT_STQT_TP32_PROD_M
      ,NVL(DGT_STQT_TP33_PROD_M,0) DGT_STQT_TP33_PROD_M
      ,NVL(DGT_STQT_TP34_PROD_M,0) DGT_STQT_TP34_PROD_M
FROM DS_SEC.CF_CUSTID A
LEFT JOIN DGT_T1 B
ON A.CUSTOMER_ID = B.PARTY_ID
LEFT JOIN DGT_T2 C
ON A.CUSTOMER_ID = C.PARTY_ID
LEFT JOIN DGT_T3 D
ON A.CUSTOMER_ID = D.PARTY_ID
LEFT JOIN DGT_T4 E
ON A.CUSTOMER_ID = E.PARTY_ID
LEFT JOIN DGT_T5 F
ON A.CUSTOMER_ID = F.PARTY_ID
LEFT JOIN DGT_T6 G
ON A.CUSTOMER_ID = G.PARTY_ID
WHERE A.YYYYMM = :ym
;
INSERT INTO DS_SEC.CF_DGT2
WITH 
--------------------------------個股詳細報價
DGT_T7 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STDTQT_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STDTQT_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T1 ELSE NULL END) DGT_STDTQT_TPS_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T1 ELSE NULL END) DGT_STDTQT_TPS_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_STDTQT_FQTPS_M_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T1 ELSE NULL END) DGT_STDTQT_FQTPS_M
    FROM(
        SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T1)SORTED FROM(
            SELECT SNAP_YYYYMM
                  ,PARTY_ID
                  ,SUBSTR(SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1),0,9)  T1
                  ,SUM(MONTH_ALL_CLICK)MONTH_ALL_CLICK
                  ,SUM(MONTH_MID_CLICK)MONTH_MID_CLICK
            FROM  PHW_CI_NEW A
            WHERE LANDING_PAGE_DESC LIKE '個股詳細報價%'
            GROUP BY SNAP_YYYYMM,PARTY_ID,SUBSTR(SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1),0,9)
            )A
        WHERE T1 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)
--------------------------------財經新聞
,  DGT_T8 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_FINNEWS_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_FINNEWS_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T3 ELSE NULL END) DGT_FINNEWS_TPS_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T3 ELSE NULL END) DGT_FINNEWS_TPS_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_FINNEWS_FQTPS_M_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T3 ELSE NULL END) DGT_FINNEWS_FQTPS_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('國際新聞','國際股市','大陸新聞','國際報價') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_FINNEWS_TP1_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('債券') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_FINNEWS_TP2_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T3 IN ('基金') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_FINNEWS_TP3_PROD_M
    FROM(
        SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T3)SORTED FROM(
            SELECT SNAP_YYYYMM
                  ,PARTY_ID
                  ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,2)+1, INSTR(LANDING_PAGE_ID, '|',1,3)-INSTR(LANDING_PAGE_ID, '|',1,2)-1) )L3
                  ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,2)+1, INSTR(LANDING_PAGE_DESC, '|',1,3)-INSTR(LANDING_PAGE_DESC, '|',1,2)-1) )T3
                  ,SUM(MONTH_ALL_CLICK)MONTH_ALL_CLICK
                  ,SUM(MONTH_MID_CLICK)MONTH_MID_CLICK
            FROM  PHW_CI_NEW A
            WHERE LANDING_PAGE_DESC LIKE '財經新聞%'
            GROUP BY SNAP_YYYYMM,PARTY_ID,SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,2)+1, INSTR(LANDING_PAGE_ID, '|',1,3)-INSTR(LANDING_PAGE_ID, '|',1,2)-1),SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,2)+1, INSTR(LANDING_PAGE_DESC, '|',1,3)-INSTR(LANDING_PAGE_DESC, '|',1,2)-1)
            )A
        WHERE T3 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)
--------------------------------類股報價
,  DGT_T9 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T5 ELSE NULL END) DGT_STCQT_TPS_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T5 ELSE NULL END) DGT_STCQT_TPS_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_STCQT_FQTPS_M_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T5 ELSE NULL END) DGT_STCQT_FQTPS_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('搜尋框%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP0_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('上市%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP1_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('上櫃%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP2_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('興櫃%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP3_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('國際金融%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP4_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('期貨報價%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP5_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('概念股%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP6_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('海外期貨%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP7_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('港股%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP8_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('熱門%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP9_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('產業%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP10_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('美股%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP11_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T5 LIKE('集團%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP12_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('搜尋框%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP0_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('上市%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP1_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('上櫃%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP2_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('興櫃%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP3_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('國際金融%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP4_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('期貨報價%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP5_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('概念股%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP6_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('海外期貨%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP7_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('港股%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP8_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('熱門%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP9_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('產業%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP10_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('美股%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP11_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') AND T5 LIKE('集團%')THEN MONTH_ALL_CLICK ELSE 0 END) DGT_STCQT_TP12_PROD_L
    FROM(
        SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T5)SORTED FROM(
            SELECT SNAP_YYYYMM
                  ,PARTY_ID
                  ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,4)+1, INSTR(LANDING_PAGE_ID, '|',1,5)-INSTR(LANDING_PAGE_ID, '|',1,4)-1) )L5
                  ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,4)+1, INSTR(LANDING_PAGE_DESC, '|',1,5)-INSTR(LANDING_PAGE_DESC, '|',1,4)-1) )T5
                  ,SUM(MONTH_ALL_CLICK)MONTH_ALL_CLICK
                  ,SUM(MONTH_MID_CLICK)MONTH_MID_CLICK
            FROM  PHW_CI_NEW A
            WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) IN ('v35')
            GROUP BY SNAP_YYYYMM,PARTY_ID,SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,4)+1, INSTR(LANDING_PAGE_ID, '|',1,5)-INSTR(LANDING_PAGE_ID, '|',1,4)-1),SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,4)+1, INSTR(LANDING_PAGE_DESC, '|',1,5)-INSTR(LANDING_PAGE_DESC, '|',1,4)-1)
            )A
        WHERE T5 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)
--------------------------------權證
, DGT_T10 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_WA_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_WA_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T5 ELSE NULL END) DGT_WA_TPS_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T5 ELSE NULL END) DGT_WA_TPS_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_WA_FQTPS_M_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T5 ELSE NULL END) DGT_WA_FQTPS_M
    FROM(
        SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T5)SORTED FROM(
            SELECT SNAP_YYYYMM
                  ,PARTY_ID
                  ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,4)+1, INSTR(LANDING_PAGE_ID, '|',1,5)-INSTR(LANDING_PAGE_ID, '|',1,4)-1) )L5
                  ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,4)+1, INSTR(LANDING_PAGE_DESC, '|',1,5)-INSTR(LANDING_PAGE_DESC, '|',1,4)-1) )T5
                  ,SUM(MONTH_ALL_CLICK)MONTH_ALL_CLICK
                  ,SUM(MONTH_MID_CLICK)MONTH_MID_CLICK
            FROM  PHW_CI_NEW A
            WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) IN ('v42')
            GROUP BY SNAP_YYYYMM,PARTY_ID,SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,4)+1, INSTR(LANDING_PAGE_ID, '|',1,5)-INSTR(LANDING_PAGE_ID, '|',1,4)-1),SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,4)+1, INSTR(LANDING_PAGE_DESC, '|',1,5)-INSTR(LANDING_PAGE_DESC, '|',1,4)-1)
            )A
        WHERE T5 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)
--------------------------------國際金融
, DGT_T11 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_INTF_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_INTF_PROD_L
          ,COUNT(CASE WHEN SNAP_YYYYMM = :ym THEN T5 ELSE NULL END) DGT_INTF_TPS_M
          ,COUNT(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN T5 ELSE NULL END) DGT_INTF_TPS_L
          ,ROUND(SUM(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN MONTH_ALL_CLICK ELSE NULL END) /SUM( CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE NULL END),4)DGT_INTF_FQTPS_M_RATIO
          ,MAX(CASE WHEN SNAP_YYYYMM = :ym AND SORTED = 1 THEN T5 ELSE NULL END) DGT_INTF_FQTPS_M
    FROM(
        SELECT A.*,RANK()OVER(PARTITION BY SNAP_YYYYMM,PARTY_ID ORDER BY MONTH_ALL_CLICK DESC,MONTH_MID_CLICK DESC,T5)SORTED FROM(
            SELECT SNAP_YYYYMM
                  ,PARTY_ID
                  ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,4)+1, INSTR(LANDING_PAGE_ID, '|',1,5)-INSTR(LANDING_PAGE_ID, '|',1,4)-1) )L5
                  ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,4)+1, INSTR(LANDING_PAGE_DESC, '|',1,5)-INSTR(LANDING_PAGE_DESC, '|',1,4)-1) )T5
                  ,SUM(MONTH_ALL_CLICK)MONTH_ALL_CLICK
                  ,SUM(MONTH_MID_CLICK)MONTH_MID_CLICK
            FROM  PHW_CI_NEW A
            WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) IN ('v65')
            GROUP BY SNAP_YYYYMM,PARTY_ID,SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,4)+1, INSTR(LANDING_PAGE_ID, '|',1,5)-INSTR(LANDING_PAGE_ID, '|',1,4)-1),SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,4)+1, INSTR(LANDING_PAGE_DESC, '|',1,5)-INSTR(LANDING_PAGE_DESC, '|',1,4)-1)
            )A
        WHERE T5 IS NOT NULL
    )A
    GROUP BY PARTY_ID
)
--------------------------------技術分析 technical analysis
, DGT_T12 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_PROD_L
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%1分線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_1LINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%5分線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_5LINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%15分線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_15LINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%30分線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_30LINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%60分線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_60LINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%日線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_DLINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%週線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_WLINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%月線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_MLINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%還原日線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_ADLINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%還原週線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_AWLINE_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym AND T1 LIKE '%還原月線%'  THEN MONTH_ALL_CLICK ELSE 0 END) DGT_TCA_AMLINE_PROD_M
    FROM(
        SELECT SNAP_YYYYMM
              ,PARTY_ID
              ,SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1)  T1
              ,SUM(MONTH_ALL_CLICK)MONTH_ALL_CLICK
              ,SUM(MONTH_MID_CLICK)MONTH_MID_CLICK
        FROM  PHW_CI_NEW A
        WHERE LANDING_PAGE_DESC LIKE '技術%'
        GROUP BY SNAP_YYYYMM,PARTY_ID,SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1)
    )A
    GROUP BY PARTY_ID
)
, DGT_T5 AS(
    SELECT PARTY_ID 
          ,SUM(CASE WHEN SNAP_YYYYMM = :ym THEN MONTH_ALL_CLICK ELSE 0 END)DGT_ALL_PROD_M
          ,SUM(CASE WHEN SNAP_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(:ym || '01', 'YYYYMMDD'), -1), 'YYYYMM') THEN MONTH_ALL_CLICK ELSE 0 END)DGT_ALL_PROD_L
    FROM(
    SELECT A.*
          ,SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) L1
          ,(SUBSTR(LANDING_PAGE_ID,INSTR(LANDING_PAGE_ID, '|',1,1)+1, INSTR(LANDING_PAGE_ID, '|',1,2)-INSTR(LANDING_PAGE_ID, '|',1,1)-1) )L2
          ,SUBSTR(LANDING_PAGE_DESC,0, INSTR(LANDING_PAGE_DESC, '|',1,1)-1)  T1
          ,(SUBSTR(LANDING_PAGE_DESC,INSTR(LANDING_PAGE_DESC, '|',1,1)+1, INSTR(LANDING_PAGE_DESC, '|',1,2)-INSTR(LANDING_PAGE_DESC, '|',1,1)-1) )T2
    FROM  PHW_CI_NEW A
    WHERE SUBSTR(LANDING_PAGE_ID,0, INSTR(LANDING_PAGE_ID, '|',1,1)-1) != 'v00'
    )A
    GROUP BY PARTY_ID
)
SELECT A.CUSTOMER_ID
      ,A.YYYYMM
      ----------------------------個股詳細報價
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_STDTQT_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_STDTQT_PROD_M_RATIO
      ,NVL(DGT_STDTQT_PROD_M,0)DGT_STDTQT_PROD_M
      ,CASE WHEN NVL(DGT_STDTQT_PROD_M,0)=0 AND NVL(DGT_STDTQT_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STDTQT_PROD_M,0) - NVL(DGT_STDTQT_PROD_L,0) END DGT_STDTQT_PROD_M_MDIFF
      ,NVL(DGT_STDTQT_TPS_M,0) DGT_STDTQT_TPS_M
      ,CASE WHEN NVL(DGT_STDTQT_TPS_M,0)=0 AND NVL(DGT_STDTQT_TPS_L,0)=0 THEN NULL ELSE NVL(DGT_STDTQT_TPS_M,0) - NVL(DGT_STDTQT_TPS_L,0) END DGT_STDTQT_TPS_M_MDIFF
      ,DGT_STDTQT_FQTPS_M_RATIO
      ,DGT_STDTQT_FQTPS_M
      
      ----------------------------財經新聞
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_FINNEWS_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_FINNEWS_PROD_M_RATIO
      ,NVL(DGT_FINNEWS_PROD_M,0)DGT_FINNEWS_PROD_M
      ,CASE WHEN NVL(DGT_FINNEWS_PROD_M,0)=0 AND NVL(DGT_FINNEWS_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_FINNEWS_PROD_M,0) - NVL(DGT_FINNEWS_PROD_L,0) END DGT_FINNEWS_PROD_M_MDIFF
      ,NVL(DGT_FINNEWS_TPS_M,0) DGT_FINNEWS_TPS_M
      ,CASE WHEN NVL(DGT_FINNEWS_TPS_M,0)=0 AND NVL(DGT_FINNEWS_TPS_L,0)=0 THEN NULL ELSE NVL(DGT_FINNEWS_TPS_M,0) - NVL(DGT_FINNEWS_TPS_L,0) END DGT_FINNEWS_TPS_M_MDIFF
      ,DGT_FINNEWS_FQTPS_M_RATIO
      ,DGT_FINNEWS_FQTPS_M
      ,NVL(DGT_FINNEWS_TP1_PROD_M,0) DGT_FINNEWS_TP1_PROD_M
      ,NVL(DGT_FINNEWS_TP2_PROD_M,0) DGT_FINNEWS_TP2_PROD_M
      ,NVL(DGT_FINNEWS_TP3_PROD_M,0) DGT_FINNEWS_TP3_PROD_M
      
      ----------------------------類股報價
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_STCQT_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_STCQT_PROD_M_RATIO
      ,NVL(DGT_STCQT_PROD_M,0)DGT_STCQT_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_PROD_M,0)=0 AND NVL(DGT_STCQT_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_PROD_M,0) - NVL(DGT_STCQT_PROD_L,0) END DGT_STCQT_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TPS_M,0) DGT_STCQT_TPS_M
      ,CASE WHEN NVL(DGT_STCQT_TPS_M,0)=0 AND NVL(DGT_STCQT_TPS_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TPS_M,0) - NVL(DGT_STCQT_TPS_L,0) END DGT_STCQT_TPS_M_MDIFF
      ,DGT_STCQT_FQTPS_M_RATIO
      ,DGT_STCQT_FQTPS_M
      ,NVL(DGT_STCQT_TP0_PROD_M,0) DGT_STCQT_TP0_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP0_PROD_M,0)=0 AND NVL(DGT_STCQT_TP0_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP0_PROD_M,0) - NVL(DGT_STCQT_TP0_PROD_L,0) END DGT_STCQT_TP0_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP1_PROD_M,0) DGT_STCQT_TP1_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP1_PROD_M,0)=0 AND NVL(DGT_STCQT_TP1_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP1_PROD_M,0) - NVL(DGT_STCQT_TP1_PROD_L,0) END DGT_STCQT_TP1_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP2_PROD_M,0) DGT_STCQT_TP2_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP2_PROD_M,0)=0 AND NVL(DGT_STCQT_TP2_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP2_PROD_M,0) - NVL(DGT_STCQT_TP2_PROD_L,0) END DGT_STCQT_TP2_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP3_PROD_M,0) DGT_STCQT_TP3_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP3_PROD_M,0)=0 AND NVL(DGT_STCQT_TP3_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP3_PROD_M,0) - NVL(DGT_STCQT_TP3_PROD_L,0) END DGT_STCQT_TP3_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP4_PROD_M,0) DGT_STCQT_TP4_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP4_PROD_M,0)=0 AND NVL(DGT_STCQT_TP4_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP4_PROD_M,0) - NVL(DGT_STCQT_TP4_PROD_L,0) END DGT_STCQT_TP4_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP5_PROD_M,0) DGT_STCQT_TP5_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP5_PROD_M,0)=0 AND NVL(DGT_STCQT_TP5_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP5_PROD_M,0) - NVL(DGT_STCQT_TP5_PROD_L,0) END DGT_STCQT_TP5_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP6_PROD_M,0) DGT_STCQT_TP6_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP6_PROD_M,0)=0 AND NVL(DGT_STCQT_TP6_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP6_PROD_M,0) - NVL(DGT_STCQT_TP6_PROD_L,0) END DGT_STCQT_TP6_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP7_PROD_M,0) DGT_STCQT_TP7_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP7_PROD_M,0)=0 AND NVL(DGT_STCQT_TP7_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP7_PROD_M,0) - NVL(DGT_STCQT_TP7_PROD_L,0) END DGT_STCQT_TP7_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP8_PROD_M,0) DGT_STCQT_TP8_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP8_PROD_M,0)=0 AND NVL(DGT_STCQT_TP8_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP8_PROD_M,0) - NVL(DGT_STCQT_TP8_PROD_L,0) END DGT_STCQT_TP8_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP9_PROD_M,0) DGT_STCQT_TP9_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP9_PROD_M,0)=0 AND NVL(DGT_STCQT_TP9_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP9_PROD_M,0) - NVL(DGT_STCQT_TP9_PROD_L,0) END DGT_STCQT_TP9_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP10_PROD_M,0) DGT_STCQT_TP10_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP10_PROD_M,0)=0 AND NVL(DGT_STCQT_TP10_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP10_PROD_M,0) - NVL(DGT_STCQT_TP10_PROD_L,0) END DGT_STCQT_TP10_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP11_PROD_M,0) DGT_STCQT_TP11_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP11_PROD_M,0)=0 AND NVL(DGT_STCQT_TP11_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP11_PROD_M,0) - NVL(DGT_STCQT_TP11_PROD_L,0) END DGT_STCQT_TP11_PROD_M_MDIFF
      ,NVL(DGT_STCQT_TP12_PROD_M,0) DGT_STCQT_TP12_PROD_M
      ,CASE WHEN NVL(DGT_STCQT_TP12_PROD_M,0)=0 AND NVL(DGT_STCQT_TP12_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_STCQT_TP12_PROD_M,0) - NVL(DGT_STCQT_TP12_PROD_L,0) END DGT_STCQT_TP12_PROD_M_MDIFF
      
      ----------------------------權證
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_WA_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_WA_PROD_M_RATIO
      ,NVL(DGT_WA_PROD_M,0)DGT_WA_PROD_M
      ,CASE WHEN NVL(DGT_WA_PROD_M,0)=0 AND NVL(DGT_WA_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_WA_PROD_M,0) - NVL(DGT_WA_PROD_L,0) END DGT_WA_PROD_M_MDIFF
      ,NVL(DGT_WA_TPS_M,0) DGT_WA_TPS_M
      ,CASE WHEN NVL(DGT_WA_TPS_M,0)=0 AND NVL(DGT_WA_TPS_L,0)=0 THEN NULL ELSE NVL(DGT_WA_TPS_M,0) - NVL(DGT_WA_TPS_L,0) END DGT_WA_TPS_M_MDIFF
      ,DGT_WA_FQTPS_M_RATIO
      ,DGT_WA_FQTPS_M
      
      ----------------------------國際金融
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_INTF_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_INTF_PROD_M_RATIO
      ,NVL(DGT_INTF_PROD_M,0)DGT_INTF_PROD_M
      ,CASE WHEN NVL(DGT_INTF_PROD_M,0)=0 AND NVL(DGT_INTF_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_INTF_PROD_M,0) - NVL(DGT_INTF_PROD_L,0) END DGT_INTF_PROD_M_MDIFF
      ,NVL(DGT_INTF_TPS_M,0) DGT_INTF_TPS_M
      ,CASE WHEN NVL(DGT_INTF_TPS_M,0)=0 AND NVL(DGT_INTF_TPS_L,0)=0 THEN NULL ELSE NVL(DGT_INTF_TPS_M,0) - NVL(DGT_INTF_TPS_L,0) END DGT_INTF_TPS_M_MDIFF
      ,DGT_INTF_FQTPS_M_RATIO
      ,DGT_INTF_FQTPS_M
      
      ----------------------------技術分析
      ,ROUND(CASE WHEN NVL(DGT_ALL_PROD_M,0) = 0 THEN NULL ELSE NVL(DGT_TCA_PROD_M,0)/NVL(DGT_ALL_PROD_M,0) END,4) DGT_TCA_PROD_M_RATIO
      ,NVL(DGT_TCA_PROD_M,0)DGT_TCA_PROD_M
      ,CASE WHEN NVL(DGT_TCA_PROD_M,0)=0 AND NVL(DGT_TCA_PROD_L,0)=0 THEN NULL ELSE NVL(DGT_TCA_PROD_M,0) - NVL(DGT_TCA_PROD_L,0) END DGT_TCA_PROD_M_MDIFF
      ,NVL(DGT_TCA_1LINE_PROD_M,0) DGT_TCA_1LINE_PROD_M
      ,NVL(DGT_TCA_5LINE_PROD_M,0) DGT_TCA_5LINE_PROD_M
      ,NVL(DGT_TCA_15LINE_PROD_M,0) DGT_TCA_15LINE_PROD_M
      ,NVL(DGT_TCA_30LINE_PROD_M,0) DGT_TCA_30LINE_PROD_M
      ,NVL(DGT_TCA_60LINE_PROD_M,0) DGT_TCA_60LINE_PROD_M
      ,NVL(DGT_TCA_DLINE_PROD_M,0) DGT_TCA_DLINE_PROD_M
      ,NVL(DGT_TCA_WLINE_PROD_M,0) DGT_TCA_WLINE_PROD_M
      ,NVL(DGT_TCA_MLINE_PROD_M,0) DGT_TCA_MLINE_PROD_M
      ,NVL(DGT_TCA_ADLINE_PROD_M,0) DGT_TCA_ADLINE_PROD_M
      ,NVL(DGT_TCA_AWLINE_PROD_M,0) DGT_TCA_AWLINE_PROD_M
      ,NVL(DGT_TCA_AMLINE_PROD_M,0) DGT_TCA_AMLINE_PROD_M
FROM DS_SEC.CF_CUSTID A
LEFT JOIN DGT_T5 F
ON A.CUSTOMER_ID = F.PARTY_ID
LEFT JOIN DGT_T7 H
ON A.CUSTOMER_ID = H.PARTY_ID
LEFT JOIN DGT_T8 I
ON A.CUSTOMER_ID = I.PARTY_ID
LEFT JOIN DGT_T9 J
ON A.CUSTOMER_ID = J.PARTY_ID
LEFT JOIN DGT_T10 K
ON A.CUSTOMER_ID = K.PARTY_ID
LEFT JOIN DGT_T11 L
ON A.CUSTOMER_ID = L.PARTY_ID
LEFT JOIN DGT_T12 M
ON A.CUSTOMER_ID = M.PARTY_ID
WHERE A.YYYYMM = :ym
;
drop table PHW_CI_new purge;
